#!/usr/bin/env bash
# Interactive environment setup for the S-MFU harness.
#
# Usage:
#   source ./setup_env.sh   # exports variables into the current shell
#   ./setup_env.sh          # writes .env.s_mfu; source it afterward

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.s_mfu"

echo "=== S-MFU Environment Setup ==="
echo "Current location:"
pwd
echo ""
echo "Repo location:"
echo "  ${SCRIPT_DIR}"
echo ""

prompt_path() {
    local var_name="$1"
    local prompt="$2"
    local default_value="$3"
    local value

    read -r -e -p "${prompt} [${default_value}]: " value
    value="${value:-${default_value}}"
    printf -v "${var_name}" '%s' "${value}"
}

prompt_optional_path() {
    local var_name="$1"
    local prompt="$2"
    local value

    read -r -e -p "${prompt} [leave blank to skip]: " value
    printf -v "${var_name}" '%s' "${value}"
}

quote_export() {
    local name="$1"
    local value="$2"
    if [[ -n "${value}" ]]; then
        printf 'export %s=%q\n' "${name}" "${value}"
    fi
}

ensure_dir() {
    local path="$1"
    if [[ -n "${path}" ]]; then
        mkdir -p "${path}"
    fi
}

ensure_file() {
    local path="$1"
    if [[ -n "${path}" ]]; then
        mkdir -p "$(dirname "${path}")"
        touch "${path}"
    fi
}

prompt_path HF_HOME_PATH "HF cache directory (HF_HOME)" "${HF_HOME:-${HOME}/.cache/huggingface}"
prompt_path RESULTS_DIR_PATH "Results directory (RESULTS_DIR)" "${RESULTS_DIR:-${SCRIPT_DIR}/results}"
prompt_path SWEEP_CONFIG_PATH_VALUE "Sweep config file (SWEEP_CONFIG)" "${SWEEP_CONFIG:-${SCRIPT_DIR}/sweep_config.yaml}"
prompt_path CHECKPOINT_PATH_VALUE "Checkpoint file (CHECKPOINT_PATH)" "${CHECKPOINT_PATH:-${RESULTS_DIR_PATH}/checkpoint.yaml}"
prompt_path EXPERT_RECORDS_PATH "Expert records directory (SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR)" "${SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR:-${RESULTS_DIR_PATH}/expert_records}"

echo ""
echo "Optional dataset source files:"
prompt_optional_path SHAREGPT_PATH "ShareGPT local JSON/JSONL file (S_MFU_SHAREGPT_PATH)"
prompt_optional_path AZURE_PATH "Azure local CSV/JSON/JSONL trace file (S_MFU_AZURE_CHAT_PATH)"
prompt_optional_path SWEBENCH_PATH "SWE-Bench local JSON/JSONL file (S_MFU_SWEBENCH_PATH)"

echo ""
echo "Creating directories/files..."
ensure_dir "${HF_HOME_PATH}"
ensure_dir "${RESULTS_DIR_PATH}"
ensure_dir "${EXPERT_RECORDS_PATH}"
ensure_file "${CHECKPOINT_PATH_VALUE}"
ensure_file "${SWEEP_CONFIG_PATH_VALUE}"
ensure_file "${SHAREGPT_PATH}"
ensure_file "${AZURE_PATH}"
ensure_file "${SWEBENCH_PATH}"

{
    echo "# Generated by setup_env.sh"
    echo "# Source this file before running the harness:"
    echo "#   source ${ENV_FILE}"
    quote_export HF_HOME "${HF_HOME_PATH}"
    quote_export RESULTS_DIR "${RESULTS_DIR_PATH}"
    quote_export SWEEP_CONFIG "${SWEEP_CONFIG_PATH_VALUE}"
    quote_export CHECKPOINT_PATH "${CHECKPOINT_PATH_VALUE}"
    quote_export SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR "${EXPERT_RECORDS_PATH}"
    quote_export S_MFU_SHAREGPT_PATH "${SHAREGPT_PATH}"
    quote_export S_MFU_AZURE_CHAT_PATH "${AZURE_PATH}"
    quote_export S_MFU_SWEBENCH_PATH "${SWEBENCH_PATH}"
} > "${ENV_FILE}"

echo ""
echo "Wrote environment file:"
echo "  ${ENV_FILE}"
echo ""
echo "Configured paths:"
echo "  HF_HOME      = ${HF_HOME_PATH}"
echo "  RESULTS_DIR  = ${RESULTS_DIR_PATH}"
echo "  SWEEP_CONFIG = ${SWEEP_CONFIG_PATH_VALUE}"
echo "  CHECKPOINT   = ${CHECKPOINT_PATH_VALUE}"
echo "  EXPERT_RECORDS = ${EXPERT_RECORDS_PATH}"
[[ -n "${SHAREGPT_PATH}" ]] && echo "  S_MFU_SHAREGPT_PATH = ${SHAREGPT_PATH}"
[[ -n "${AZURE_PATH}" ]] && echo "  S_MFU_AZURE_CHAT_PATH = ${AZURE_PATH}"
[[ -n "${SWEBENCH_PATH}" ]] && echo "  S_MFU_SWEBENCH_PATH = ${SWEBENCH_PATH}"

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    echo ""
    echo "Environment variables exported into the current shell."
else
    echo ""
    echo "To use these values in your current shell, run:"
    echo "  source ${ENV_FILE}"
fi
