benchmark_type: prefill
dataset_names:
- longbench_v2
metrics:
- em
model_id: deepseek-ai/DeepSeek-V2-Lite-Chat
precision: bfloat16
dataset_split: train
num_samples: 200
fixed_length_mode: true
target_input_tokens: 13312
target_output_tokens: 1
prefill_mode: null
chunked_prefill_size: null
max_prefill_tokens: null
mem_fraction_static: null
max_batch_size: null
